### ISSUE TITLE
Error: Authentication Failure ([ElementNotInteractableException] Message: element not interactable

### ISSUE THREAD

**Issue by tpengandrew** [smkent/safeway-coupons#100]
Clipping coupons for Safeway account xxxx.xxx@gmail.com
Connect to safeway.com
Decline cookie prompt
Open Sign In sidebar
Open Sign In form
Populate Sign In form
Error: Authentication Failure ([ElementNotInteractableException] Message: element not interactable
  (Session info: chrome=114.0.5735.133)
Stacktrace:
#0 0x55eddd3734e3 <unknown>
#1 0x55eddd0a2b00 <unknown>
#2 0x55eddd0d952c <unknown>
#3 0x55eddd0d8b0a <unknown>
#4 0x55eddd0fe012 <unknown>
#5 0x55eddd0d4b03 <unknown>
#6 0x55eddd0fe1de <unknown>
#7 0x55eddd11630e <unknown>
#8 0x55eddd0fdde3 <unknown>
#9 0x55eddd0d32dd <unknown>
#10 0x55eddd0d434e <unknown>
#11 0x55eddd3333e4 <unknown>
#12 0x55eddd3373d7 <unknown>
#13 0x55eddd341b20 <unknown>
#14 0x55eddd338023 <unknown>
#15 0x55eddd3061aa <unknown>
#16 0x55eddd35c6b8 <unknown>
#17 0x55eddd35c847 <unknown>
#18 0x55eddd36c243 <unknown>
#19 0x7ff590694b43 <unknown>

**Comment by jamesderlin** [comment]
I've been consistently getting other failures over the past few days.  They're not always the same:
```
Clipping coupons for Safeway account REDACTED
Connect to safeway.com
Decline cookie prompt
Open Sign In sidebar
Open Sign In form
Error: Authentication Failure ([TimeoutException] Message: 
))
```
and
```
Error: Authentication Failure ([StaleElementReferenceException] Message: stale element reference: stale element not found
  (Session info: chrome=114.0.5735.198); For documentation on this error, please
 visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#
stale-element-reference-exception
Stacktrace:
#0 0x55ce36acf4e3 <unknown>
#1 0x55ce367fec76 <unknown>
#2 0x55ce3680ba71 <unknown>
...
```

**Comment by qtang** [comment]
I am running this via the docker container method and was consistently receiving a Stale Element Reference Exception. Here's my quick and dirty workaround:

1. Change session.py line 95 from url = "https://www.safeway.com" to url = "https://www.safeway.com/account/sign-in.html?goto=/foru/coupons-deals.html"
2. Comment out lines 108-119.

![Screen Shot 2023-09-13 at 10 31 34 AM](https://github.com/smkent/safeway-coupons/assets/1197879/26234f66-826a-49b9-9869-5a9130e37bab)

**Comment by tpengandrew** [comment]
This works for me -- thanks!

> I am running this via the docker container method and was consistently receiving a Stale Element Reference Exception. Here's my quick and dirty workaround:
> 
>     1. Change session.py line 95 from url = "https://www.safeway.com" to url = "https://www.safeway.com/account/sign-in.html?goto=/foru/coupons-deals.html"
> 
>     2. Comment out lines 108-119.
> 
> 
> ![Screen Shot 2023-09-13 at 10 31 34 AM](https://user-images.githubusercontent.com/1197879/267740803-26234f66-826a-49b9-9869-5a9130e37bab.png)

**Comment by smkent** [comment]
Hi all, thanks for the bug report! I believe this is now fixed via https://github.com/smkent/safeway-coupons/pull/103 within release version 0.2.7. Please let me know if you continue to experience any issues.
