### ISSUE TITLE
Error: Authentication Failure (I/O operation on closed file)

### ISSUE THREAD

**Issue by namkyup** [smkent/safeway-coupons#102]
Docker with [#100](https://github.com/smkent/safeway-coupons/issues/100) changes.

```
safeway-coupons  --accounts-config "/accounts_file"
Clipping coupons for Safeway account xxx
Connect to safeway.com
Decline cookie prompt
Populate Sign In form
Deselect Keep Me Signed In
Click Sign In button
Wait for signed in landing page to load
Retrieve session information
sendmail: bad address ''
Error: Authentication Failure (I/O operation on closed file)
```

**Comment by smkent** [comment]
Hi, thanks for the report! I believe this has to do with using undetected_chromedriver as a context manager. I've reworked the driver code and I believe this is now solved via https://github.com/smkent/safeway-coupons/pull/103 within release version 0.2.7. Please let me know if you continue to run into this issue.
