### ISSUE TITLE
browser version not matching chromedriver

### ISSUE THREAD

**Issue by borgified** [smkent/safeway-coupons#109]
```
safeway-coupons-safeway-coupons_test-1    | from session not created: This version of ChromeDriver only supports Chrome version 121
safeway-coupons-safeway-coupons_test-1    | Current browser version is 120.0.6099.109
```
because of this mismatch i couldnt get it to run. i tried using ghcr.io/smkent/safeway-coupons:latest, 0.2.9 and 0.2.8 with similar mismatching results.

i think this is because the webdriver-manager is not 4.0.1. after i made this change and rebuilt the container, i was able to make it log into the site:

```
$ git diff
diff --git a/pyproject.toml b/pyproject.toml
index 16d307b..9fce79b 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -22,7 +22,7 @@ python = "^3.8"
 dataclasses-json = "*"
 requests = "*"
 selenium = "^4.10"
-webdriver-manager = "^3.8.6"
+webdriver-manager = "^4.0.1"
 undetected-chromedriver = "^3.5.0"
```

im not familiar with webdriver-manager so im not sure if this is the right solution, if it is, im happy to create a PR if it helps.

**Comment by smkent** [comment]
I'm seeing this too and I've been confused by similar issues in the past, which have been resolved by rebuilding the container.

[I found this](https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1558#issuecomment-1719065725) which explains that undetected-chromedriver (oddly) downloads the driver at runtime. Apparently it's possible to pin the Chrome version in code, so I'll look at doing that dynamically based on the version downloaded at container build time. I wonder if there's a way to pre-download and/or permanently cache the driver as well.

**Comment by smkent** [comment]
https://github.com/smkent/safeway-coupons/pull/110 should resolve this.

**Comment by smkent** [comment]
v0.2.11 is released with that change. Give it a try and let me know if it works!

**Comment by borgified** [comment]
works great now thank you so much
