### ISSUE TITLE
"Invalid Store ID in Request parameter" error from HTTP request

### ISSUE THREAD

**Issue by jillh510** [smkent/safeway-coupons#15]
The call to the nimbus.safeway.com URL (line 254) returns an error: 
`{"errors":[{"code":"EMJO02030E","msg":"Invalid Store ID in Request parameter."}]}`

This started happening a few days ago.

**Comment by smkent** [comment]
Safeway's site seems to have changed. I reworked the script for #16. I believe this issue is a duplicate of that one. Feel free to reopen this issue if it's still broken after the update.
