### ISSUE TITLE
Exception: Offers Not Found

### ISSUE THREAD

**Issue by nitaro02** [smkent/safeway-coupons#16]
I am new to commenting on Github so my apologies if I'm breaking any conventions...

This script was running great up until a few days ago.  When running it, I now get the following:

Exception clipping coupons: Offers not found
Traceback (most recent call last):
  File "safeway-coupons.py", line 258, in _clip_coupons
    raise Exception('Offers not found')
Exception: Offers not found

Thanks for any help!

**EDIT: I was getting a longer error, I downloaded the most recent version of this script and replaced my older version, now I'm only getting the shorter error above regarding the offers not found.**

**Comment by zhamoytin** [comment]
having same issue...

**Comment by Allmight3** [comment]
Just came here to post the same thing. Started around the same time you mentioned.

I had it print the error and it's an error someone here posted about a week ago:

Data: {"errors":[{"code":"EMJO02030E","msg":"Invalid Store ID in Request parameter."}]}

**Comment by smkent** [comment]
It appears that the coupon clipping system changed. I modified the script and it seems to work with the current site. Let me know if there are still any issues!
