### ISSUE TITLE
Items You May Like not clipped

### ISSUE THREAD

**Issue by ebiancarelli** [smkent/safeway-coupons#17]
Script works great, but the Items You May Like are not selected. I've tried to figure out why, and from what I can tell, the 'status' is 'C' even though they are not added.

![Screen Shot 2020-03-14 at 8 23 51 AM](https://user-images.githubusercontent.com/156859/76683903-37609900-65cd-11ea-869e-6157cc094a0b.png)

Any idea on how to add these?

**Comment by smkent** [comment]
Hi @ebiancarelli, apologies for the (very) long delay. I finally had some time to give safeway-coupons some love. I've mostly rewritten it including updating the HTTP endpoints used to clip coupons.

Safeway has shuffled the coupons organization on their site. I don't believe "Items you may like" is a section anymore.

Feel free to give the updated script a try and let me know how you like it. I've published safeway-coupons as a package, so you can now `pip install safeway-coupons` to try it out!

**Comment by ebiancarelli** [comment]
🙌  you rock! I'll take another look!
