### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by Allmight3** [smkent/safeway-coupons#20]
The original error that comes up:

> Exception: Expecting value: line 1 column 1 (char 0)
> Traceback (most recent call last):
>   File "safeway-coupons.py", line 96, in __init__
>     self._login()
>   File "safeway-coupons.py", line 185, in _login
>     rsp_data = json.loads(rsp.content.decode('UTF-8'))
>   File "C:\Python3\lib\json\__init__.py", line 348, in loads
>     return _default_decoder.decode(s)
>   File "C:\Python3\lib\json\decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "C:\Python3\lib\json\decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

I took a look at why there was a JSON error and it appears that there is no longer a successful request being sent to login. Here is a print of the rsp.content:

> b'<html style="height:100%"><head><META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW"><meta name="format-detection" content="telephone=no"><meta name="viewport" content="initial-scale=1.0"><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"><script type="text/javascript" src="/_Incapsula_Resource?SWJIYLWA=719d34d31c8e3a6e6fffd425f7e032f3"></script></head><body style="margin:0px;height:100%"><iframe id="main-iframe" src="/_Incapsula_Resource?CWUDNSAI=22&xinfo=3-18966364-0%200NNN%20RT%281590123933415%20353%29%20q%280%20-1%20-1%20-1%29%20r%280%20-1%29%20B16%20U5&incident_id=523000080070749646-111243874953527811&edet=16&cinfo=ffffffff&rpinfo=0" frameborder=0 width="100%" height="100%" marginheight="0px" marginwidth="0px">Request unsuccessful. Incapsula incident ID: 523000080070749646-111243874953527811</iframe></body></html>'

I'm using the latest commit I see from Feb 19 and I am using python 3.7.5.

**Comment by jillh510** [comment]
I'm seeing the same thing. 403 error returned from the call to 
`        rsp = self._run_request(('https://www.safeway.com/iaaw/service/'
                                 'authenticate'),
                                json_data=login_data, headers=headers)
`

**Comment by smkent** [comment]
It appears Safeway has started using Okta for login (the login form now posts to `albertsons.okta.com`). I'll need to do some investigation.

**Comment by Allmight3** [comment]
@jamesderlin for now I am just using a headless selenium chrome browser to clip them. 

Not as nice but it'll have to do until @smkent has a chance to fix the login.

**Comment by jmacknet** [comment]
Looks like somebody figured it out. I may try to merge the new auth part.

https://blog.jonlu.ca/posts/safeway

**Comment by jmacknet** [comment]
Just created a new pull request that updates for the new authentication method. It's basically as described in the previous link, though the blog post glossed over many critical details.

**Comment by tieubao81** [comment]
I'm not sure if deleting ORIGIN completely did the trick.  It was able to clip, but not all.  I visited the safeway J4U website and there's still a lot of unclipped coupons.  Especially in the Personalized Price and Special Offer.  After you click load more, it seems to stopped clipping those coupons all together.

**Comment by jmacknet** [comment]
@tieubao81, I think there's a secondary issue with an API change. The new URL for the coupon gallery is https://www.safeway.com/abs/pub/web/j4u/api/ecomgallery, and it has a different JSON format. I initially reworked the code to use the new ecomgallery URL before finding out that the old URL still worked with the ORIGIN header removed. I thought all the coupons were being clipped with the old URL, but it looks like they may not be if you're still getting unclipped coupons. It's not hard to switch to the new URL, just a couple minor changes to address the new JSON layout.

**Comment by jmacknet** [comment]
Took another look at the unclipped coupons and it looks like they are actually being clipped, but show up as unclipped on the browser due to the new use of localstorage caching of the coupon list. To force the cache to clear, I deleted all my cookies and logged in again and the coupons that were previously showing unclipped were actually clipped. So I think the coupon clipper is working fine.

**Comment by machowsk** [comment]
For what it's worth, I pulled @jmacknet's Okta changes in [PR21 ](https://github.com/smkent/safeway-coupons/pull/21) into my fork of this project and it's working fine. Thanks, jmacknet!

**Comment by smkent** [comment]
Thanks to @jmacknet for providing a fix in #21!
