### ISSUE TITLE
Script runs with no results

### ISSUE THREAD

**Issue by diabWH3** [smkent/safeway-coupons#24]
Details:
* In the Windows 10 environment
* `accounts_config` and `safeway-coupons` are in the same directory
* Calling the script using `python3 safeway-coupons -c "G:\My Drive\Temp\Safeway Coupon Clipper\accounts_config"`
* The script seems to run for a few seconds, but there is no visible change, and then PowerShell shows a new command line
* No browser opens and the "Items You May Like" coupons are all still unselected

![2022-02-02 20_54_30-G__My Drive_Temp_Safeway Coupon Clipper_accounts_config - Notepad++  Administrat](https://user-images.githubusercontent.com/49632769/152283665-5622993f-8a0f-48b0-8878-ba1c5002c567.jpg)

![2022-02-02 21_01_00-Coupons and Deals _ Safeway](https://user-images.githubusercontent.com/49632769/152284103-0846896e-d988-439b-8115-d48368ceb889.jpg)

**Comment by smkent** [comment]
Hi @diabWH3, thanks for the bug report! I finally had some time to give safeway-coupons some love. I've mostly rewritten it including updating the HTTP endpoints used to clip coupons.

Feel free to give it another try and let me know if you still run into any issues. I've published safeway-coupons as a package, so you can now `pip install safeway-coupons` to try it out!
