### ISSUE TITLE
Coupons not added to the safeway card

### ISSUE THREAD

**Issue by zhamoytin** [smkent/safeway-coupons#3]
Script is running fine and clipping coupons but when you log into your safeway account no coupons actually added to the card.

**Comment by smkent** [comment]
It looks like part of the coupon clipping system on Safeway's site changed. I updated the script to work with the current site in 6f0798d2ccf0cc21abda0a687d65216a67390787.

I tested coupon clipping but I didn't test Your Club Specials items (all of the YCS items in my account are already selected). Please let me know if anything doesn't work.

Thanks for the bug report!

**Comment by borgified** [comment]
thank you for the update

**Comment by smkent** [comment]
I don't think the previous update was working quite right, so I just made some additional fixes.

**Comment by zhamoytin** [comment]
It works perfect now, thanks!

**Comment by zhamoytin** [comment]
Actually, can you please check why it doesn't show the price for "coupons for items you buy"
now:
Coupon: O Organics Fresh Rosemary 1-oz. (, expires: 2017.03.07)
but it should looks like:
Coupon: O Organics Fresh Rosemary 1-oz. (**Personalized Price $1.69**, expires: 2017.03.07)

**Comment by smkent** [comment]
@zhamoytin: I just updated the coupon type detection in the coupon details retrieval. Give the updated version a try.

**Comment by zhamoytin** [comment]
Verified - now script printing prices, thank you!
