### ISSUE TITLE
Coupons not added to the safeway card#2

### ISSUE THREAD

**Issue by zhamoytin** [smkent/safeway-coupons#4]
Script is running fine and clipping coupons but when you log into your safeway account no coupons actually added to the card.

**Comment by smkent** [comment]
It looks like Safeway deployed an updated coupon clipping service on `nimbus.safeway.com` but also left the existing service up on `www.safeway.com`, which no longer seems to have any effect. I updated the script to point to `nimbus.safeway.com`. Coupon clipping is working in my account again, let me know if it works for you!
