### ISSUE TITLE
"Exception: Offers not found" when running safeway-coupons

### ISSUE THREAD

**Issue by jamesderlin** [smkent/safeway-coupons#5]
I think starting around August 22, 2017, safeway-coupons started failing with an "Offers not found" exception:

Safeway account: xxx@example.com
Exception clipping coupons: Offers not found
Traceback (most recent call last):
  File "/home/someuser/src/git/other/safeway-coupons/safeway-coupons", line 262,
 in _clip_coupons
    raise Exception('Offers not found')
Exception: Offers not found

**Comment by smkent** [comment]
I believe 1f03f5fb5a700855522ae9bcf82999ba3369ce11 should fix this issue. If it doesn't work, let me know!
