### ISSUE TITLE
Could safeway-coupons set a non-zero exit code on failure?

### ISSUE THREAD

**Issue by jamesderlin** [smkent/safeway-coupons#6]
After issue #5, I noticed that safeway-coupons returns an exit code of 0 even though it failed from raised exceptions.  Would you be open to changing that behavior?

I am aware that safeway-coupons has an email notification system, but I don't have sendmail set up (and I don't want the daily email when everything is working), so I have a different notification system set up around safeway-coupons.  It would be great if I could use the exit code to easily determine if safeway-coupons failed.

**Comment by smkent** [comment]
This is added in ad13ff67133fdf560772e4b3975fe4b7d829f907.
