### ISSUE TITLE
Error: Authentication Failure (Message: no such element: Unable to locate element: {"method":"xpath","selector":"//button [contains(text(), 'Necessary Only')]"}

### ISSUE THREAD

**Issue by zhamoytin** [smkent/safeway-coupons#84]
Still not working with the latest update
Running from portainer.

`root@32c402ff36d4:/# safeway-coupons -c accounts_file -d -n
Clipping coupons for Safeway account my_email@gmail.com
Connect to safeway.com
Would send email to my_email@gmail.com
>>>>>>
Safeway account: my_email@gmail.com
Error: Authentication Failure (Message: no such element: Unable to locate element: {"method":"xpath","selector":"//button [contains(text(), 'Necessary Only')]"}
  (Session info: chrome=114.0.5735.198); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x563b4f3834e3 <unknown>
#1 0x563b4f0b2c76 <unknown>
#2 0x563b4f0eec96 <unknown>
#3 0x563b4f0eedc1 <unknown>
#4 0x563b4f1287f4 <unknown>
#5 0x563b4f10e03d <unknown>
#6 0x563b4f12630e <unknown>
#7 0x563b4f10dde3 <unknown>
#8 0x563b4f0e32dd <unknown>
#9 0x563b4f0e434e <unknown>
#10 0x563b4f3433e4 <unknown>
#11 0x563b4f3473d7 <unknown>
#12 0x563b4f351b20 <unknown>
#13 0x563b4f348023 <unknown>
#14 0x563b4f3161aa <unknown>
#15 0x563b4f36c6b8 <unknown>
#16 0x563b4f36c847 <unknown>
#17 0x563b4f37c243 <unknown>
#18 0x7fab524e6fd4 <unknown>
)
<<<<<<
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/safeway_coupons/session.py", line 52, in __init__
    self._login(account)
  File "/usr/local/lib/python3.11/site-packages/safeway_coupons/session.py", line 81, in _login
    button = driver.find_element(
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 740, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 346, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//button [contains(text(), 'Necessary Only')]"}
  (Session info: chrome=114.0.5735.198); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x563b4f3834e3 <unknown>
#1 0x563b4f0b2c76 <unknown>
#2 0x563b4f0eec96 <unknown>
#3 0x563b4f0eedc1 <unknown>
#4 0x563b4f1287f4 <unknown>
#5 0x563b4f10e03d <unknown>
#6 0x563b4f12630e <unknown>
#7 0x563b4f10dde3 <unknown>
#8 0x563b4f0e32dd <unknown>
#9 0x563b4f0e434e <unknown>
#10 0x563b4f3433e4 <unknown>
#11 0x563b4f3473d7 <unknown>
#12 0x563b4f351b20 <unknown>
#13 0x563b4f348023 <unknown>
#14 0x563b4f3161aa <unknown>
#15 0x563b4f36c6b8 <unknown>
#16 0x563b4f36c847 <unknown>
#17 0x563b4f37c243 <unknown>
#18 0x7fab524e6fd4 <unknown>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/safeway-coupons", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/safeway_coupons/app.py", line 101, in main
    sc.clip_for_account(account)
  File "/usr/local/lib/python3.11/site-packages/safeway_coupons/safeway.py", line 36, in clip_for_account
    swy = SafewayClient(account, self.debug_dir)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/safeway_coupons/client.py", line 17, in __init__
    self.session = LoginSession(account, debug_dir)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/safeway_coupons/session.py", line 58, in __init__
    raise AuthenticationFailure(e, account) from e
safeway_coupons.errors.AuthenticationFailure: Authentication Failure (Message: no such element: Unable to locate element: {"method":"xpath","selector":"//button [contains(text(), 'Necessary Only')]"}
  (Session info: chrome=114.0.5735.198); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x563b4f3834e3 <unknown>
#1 0x563b4f0b2c76 <unknown>
#2 0x563b4f0eec96 <unknown>
#3 0x563b4f0eedc1 <unknown>
#4 0x563b4f1287f4 <unknown>
#5 0x563b4f10e03d <unknown>
#6 0x563b4f12630e <unknown>
#7 0x563b4f10dde3 <unknown>
#8 0x563b4f0e32dd <unknown>
#9 0x563b4f0e434e <unknown>
#10 0x563b4f3433e4 <unknown>
#11 0x563b4f3473d7 <unknown>
#12 0x563b4f351b20 <unknown>
#13 0x563b4f348023 <unknown>
#14 0x563b4f3161aa <unknown>
#15 0x563b4f36c6b8 <unknown>
#16 0x563b4f36c847 <unknown>
#17 0x563b4f37c243 <unknown>
#18 0x7fab524e6fd4 <unknown>
)
root@32c402ff36d4:/# `

**Comment by smkent** [comment]
Thanks for the report! I bet Safeway's web site isn't presenting your browser with the cookie opt-out prompt. It should be easy enough for me to make that part of the flow non-fatal so login can continue. Stay tuned!

**Comment by zhamoytin** [comment]
You are awesome!

> Thanks for the report! I bet Safeway's web site isn't presenting your browser with the cookie opt-out prompt. It should be easy enough for me to make that part of the flow non-fatal so login can continue. Stay tuned!

**Comment by smkent** [comment]
This may work: https://github.com/smkent/safeway-coupons/pull/86
